- Dockerfile.ocp
- Dockerfile.promtail.ocp
- OWNERS
Adding OWNERS file and downstream Dockerfiles.
Dockerfiles are split from `build/Dockerfile` and use UBI as a base.
This is needed to set up prow correctly. Merge with GitHub button as prow commands are not available until https://github.com/openshift/release/pull/4672 is merged.
/cc @brancz
> *: add OWNERS file and downstream Dockerfiles

- Dockerfile.ocp
- Dockerfile.promtail.ocp
This updates the Dockerfiles in main to match `upstream-2.4.2`.
One question:
- Is `4.10` is correct OCP version to target or should it be a newer one?
> Update rhel8 based Dockerfiles for Loki

- operator/CHANGELOG.md
- operator/apis/config/v1/projectconfig_types.go
- operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/openshift/controller_manager_config.yaml
- operator/docs/lokistack/sop.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/build_test.go
- operator/internal/manifests/compactor.go
- operator/internal/manifests/distributor.go
- operator/internal/manifests/gateway.go
- operator/internal/manifests/gateway_tenants_test.go
- operator/internal/manifests/indexgateway.go
- operator/internal/manifests/ingester.go
- operator/internal/manifests/internal/alerts/build.go
- operator/internal/manifests/internal/alerts/prometheus-alerts.yaml
- operator/internal/manifests/internal/alerts/testdata/test.yaml
- operator/internal/manifests/openshift/opa_openshift.go
- operator/internal/manifests/querier.go
- operator/internal/manifests/query-frontend.go
- operator/internal/manifests/ruler.go
- operator/internal/manifests/var.go
The following PR backports all bugfixes introduced for `release-5.5` since `5.5.0` till today. The following upstream PRs are included:
- grafana/loki#6935
- grafana/loki#6997
- grafana/loki#6999
- grafana/loki#7000
> [release-5.5] Backport bugfixes from main

- operator/BACKPORTING.md
The following PR provides instructions for backporting Loki Operator upstream PRs into openshift/loki
> Add backport instructions

- operator/CHANGELOG.md
- operator/internal/manifests/ruler.go
The present PR is a backport of the rule TLS client configuration for the ruler
Ref: None
> [release-5.5] Backport PR grafana/loki#7214

- operator/apis/loki/v1/lokistack_types.go
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
- operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
- operator/internal/handlers/internal/storage/ca_configmap.go
- operator/internal/handlers/internal/storage/ca_configmap_test.go
- operator/internal/handlers/lokistack_create_or_update.go
- operator/internal/handlers/lokistack_create_or_update_test.go
- operator/internal/manifests/storage/configure.go
- operator/internal/manifests/storage/configure_test.go
- operator/internal/manifests/storage/options.go
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>
Title: [release-5.5] Backport PR grafana/loki#7070
Description:
This PR supports bringing up Loki in a cluster that runs behind a proxy It adds  proxy certificates to support secure traffic behind a proxy in a cluster.
Ref: [LOG-2860](https://issues.redhat.com//browse/LOG-2860)
> [release-5.5] Backport PR grafana/loki#7070

- operator/bundle/metadata/properties.yaml
The present PR backports the capability to enable release-5.5 subscriptions on OpenShift 4.12
Ref: [LOG-3119](https://issues.redhat.com//browse/LOG-3119)
> [release-5.5] Backport PR grafana/loki#7296

- Dockerfile.ocp
- Dockerfile.promtail.ocp
Preparation work to address build failures in: 
- #58
> Bump base images to Golang 1.19 and OCP 4.12

- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
(cherry picked from commit 3d2aa76349471fe528d51939cd669e0446f5db2d)
This PR adds the operators.openshift.io/valid-subscription annotation to the operator metadata.
https://issues.redhat.com/browse/LOG-3251
**Checklist**
> [release-5.5] LOG-3251: Add valid subscription annotation to metadata

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
The present PR is a backport of the correct descriptor for the `ObjectStorageTLSSpec.CAKey` field.
Ref: [LOG-3310](https://issues.redhat.com//browse/LOG-3310)
> [release-5.5] Backport PR grafana/loki#7744

- operator/CHANGELOG.md
- operator/internal/manifests/gateway.go
- operator/internal/manifests/gateway_test.go
The present PR is a backport of lokistack-gateway replica fix.
Ref: [LOG-3478](https://issues.redhat.com//browse/LOG-3478)
> [release-5.6] Backport PR grafana/loki#8068

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator-webhook-service_v1_service.yaml
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/openshift/kustomization.yaml
- operator/config/overlays/openshift/manager_webhook_patch.yaml
- operator/config/overlays/openshift/webhook_service_annotations_patch.yaml
Backport of https://github.com/grafana/loki/pull/8173 into release-5.5.
Refs: [LOG-3511](https://issues.redhat.com//browse/LOG-3511)
> [release-5.5] Remove custom webhook cert mounts for OLM-based deployment (#8173)

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator-webhook-service_v1_service.yaml
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/openshift/kustomization.yaml
- operator/config/overlays/openshift/manager_webhook_patch.yaml
- operator/config/overlays/openshift/webhook_service_annotations_patch.yaml
Backport of https://github.com/grafana/loki/pull/8173 into release-5.6.
Refs: [LOG-3510](https://issues.redhat.com//browse/LOG-3510)
> [release-5.6] Remove custom webhook cert mounts for OLM-based deployment (#8173) 

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/controllers/loki/internal/lokistack/certrotation_discovery.go
- operator/controllers/loki/internal/lokistack/ruler_config_discovery.go
- operator/controllers/loki/internal/lokistack/rules_discovery.go
- operator/controllers/loki/internal/lokistack/update.go
- operator/controllers/loki/lokistack_controller.go
- operator/controllers/loki/lokistack_controller_test.go
- operator/internal/status/lokistack.go
- operator/internal/status/lokistack_test.go
Backport of grafana/loki#8087 into `release-5.6`.
Refs: [LOG-3496](https://issues.redhat.com//browse/LOG-3496)
> [release-5.6] Fix status not updating when state of pods changes

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
This PR backports a change which allows the compactor to use gRPC instead of http for the delete requests.
Ref: https://issues.redhat.com/browse/LOG-3494
/cc @xperimental 
> [release-5.6] Backport PR grafana/loki#8265

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/internal/manifests/var.go
This PR backports the update of the Loki operand from `v2.7.1` to `v2.7.2`
Ref: [LOG-3560](https://issues.redhat.com//browse/LOG-3560)
> [release-5.6] Backport PR grafana/loki#8336

- operator/bundle/metadata/properties.yaml
The `release-5.6` branch will support up to and including OCP 4.13 based on our support policy.
Ref: [LOG-3584](https://issues.redhat.com//browse/LOG-3584)
> [release-5.6] Bump bundle OCP max version property to 4.14

- operator/CHANGELOG.md
- operator/internal/handlers/internal/gateway/tenant_configsecret.go
- operator/internal/handlers/internal/gateway/tenant_configsecret_test.go
- operator/internal/handlers/lokistack_create_or_update.go
- operator/internal/manifests/gateway.go
- operator/internal/manifests/gateway_test.go
- operator/internal/manifests/internal/config/build_test.go
This PR backports a change which allows the gateway tenant information to be stored in a secret rather than the config map.
Ref: https://issues.redhat.com/browse/LOG-3717
> [release-5.6] Backport PR grafana/loki#8577

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
The present PR is a backport of the Loki operand update from v2.7.3 to v2.7.4.
Ref: [LOG-3660](https://issues.redhat.com//browse/LOG-3660)
> [release-5.6] Backport PR grafana/loki#8771

- operator/CHANGELOG.md
- operator/internal/manifests/gateway.go
- operator/internal/manifests/gateway_test.go
The present PR is a backport of the fix that applies tolerations and nodeselector to the lokistack-gateway deployment.
Ref: [LOG-3783](https://issues.redhat.com//browse/LOG-3783)
/cc @xperimental @aminesnow 
> [release-5.6] Backport PR grafana/loki#8707

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
The present PR is a backport into `release-5.6` of:
- grafana/loki#8958
Ref: [LOG-3814](https://issues.redhat.com//browse/LOG-3814)
> [release-5.6] Backport PR grafana/loki#8958

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
The present PR is a backport of the loki operand update from `v2.7.4` to `v2.8.0`
Ref: [LOG-3909](https://issues.redhat.com//browse/LOG-3909)
> [release-5.6] Backport PR grafana/loki#9036

- operator/CHANGELOG.md
- operator/controllers/loki/lokistack_controller.go
- operator/controllers/loki/lokistack_controller_test.go
This PR is a backport of #8978, which adds a watch on the object storage secret.
ref: [LOG-3944](https://issues.redhat.com/browse/LOG-3944)
/cc @periklis
> [release-5.6] Backport PR grafana/loki#8978

- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
This changes the generated bundle to include a skipRange attribute that limits direct updates to only be able from 5.5 onwards.
[LOG-4041](https://issues.redhat.com//browse/LOG-4041)
> LOG-4041: Update skipRange to allow updating from 5.5 onwards

- operator/internal/manifests/compactor_test.go
- operator/internal/manifests/config_test.go
- operator/internal/manifests/distributor_test.go
- operator/internal/manifests/indexgateway_test.go
- operator/internal/manifests/ingester_test.go
- operator/internal/manifests/mutate_test.go
- operator/internal/manifests/querier_test.go
- operator/internal/manifests/ruler_test.go
- operator/internal/manifests/rules_config_test.go
What this PR does / why we need it**:
https://github.com/grafana/loki/pull/9433
Moves all the unit tests under operator/manifests to the manifests package making all test files now uniform.
**Checklist**
> [release-5.7] Backport PR grafana/loki#9433

- operator/internal/manifests/compactor_test.go
- operator/internal/manifests/config_test.go
- operator/internal/manifests/distributor_test.go
- operator/internal/manifests/indexgateway_test.go
- operator/internal/manifests/ingester_test.go
- operator/internal/manifests/mutate_test.go
- operator/internal/manifests/querier_test.go
- operator/internal/manifests/ruler_test.go
- operator/internal/manifests/rules_config_test.go
https://github.com/grafana/loki/pull/9433
Moves all the unit tests under operator/manifests to the manifests package making all test files now uniform.
**Checklist**
> [release-5.6] Backport PR grafana/loki#9433 

- operator/internal/manifests/compactor_test.go
- operator/internal/manifests/config_test.go
- operator/internal/manifests/distributor_test.go
- operator/internal/manifests/indexgateway_test.go
- operator/internal/manifests/ingester_test.go
- operator/internal/manifests/mutate_test.go
- operator/internal/manifests/querier_test.go
- operator/internal/manifests/ruler_test.go
- operator/internal/manifests/rules_config_test.go
https://github.com/grafana/loki/pull/9433
Moves all the unit tests under operator/manifests to the manifests package making all test files now uniform
**Checklist**
>  [release-5.5] Backport PR grafana/loki#9433

- operator/CHANGELOG.md
- operator/apis/config/v1/projectconfig_types.go
- operator/bundle/community-openshift/manifests/loki-operator-manager-config_v1_configmap.yaml
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator-manager-config_v1_configmap.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/controller_manager_config.yaml
- operator/config/overlays/openshift/controller_manager_config.yaml
- operator/controllers/loki/lokistack_controller.go
- operator/controllers/loki/lokistack_controller_test.go
- operator/docs/operator/api.md
- operator/docs/operator/feature-gates.md
- operator/internal/manifests/gateway_tenants.go
- operator/internal/manifests/gateway_tenants_test.go
- operator/internal/manifests/gateway_test.go
- operator/internal/manifests/openshift/build.go
- operator/internal/manifests/openshift/build_test.go
- operator/internal/manifests/openshift/options.go
- operator/main.go
The present PR is a backport of enabling the LokiStack Route resource by default on any OpenShift cluster (community and OCP).
Ref: [LOG-4139](https://issues.redhat.com//browse/LOG-4139)
> [release-5.7] Backport PR grafana/loki#9346

- operator/CHANGELOG.md
- operator/apis/config/v1/projectconfig_types.go
- operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml
- operator/config/overlays/openshift/controller_manager_config.yaml
- operator/controllers/loki/lokistack_controller.go
- operator/controllers/loki/lokistack_controller_test.go
- operator/docs/operator/api.md
- operator/docs/operator/feature-gates.md
- operator/internal/manifests/gateway_tenants.go
- operator/internal/manifests/gateway_tenants_test.go
- operator/internal/manifests/gateway_test.go
- operator/internal/manifests/openshift/build.go
- operator/internal/manifests/openshift/build_test.go
- operator/internal/manifests/openshift/options.go
- operator/main.go
The present PR is a backport of enabling the LokiStack Route resource by default on any OpenShift cluster (community and OCP).
Ref: [LOG-4140](https://issues.redhat.com//browse/LOG-4140)
> [release-5.6] Backport PR grafana/loki#9346

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
- operator/docs/operator/api.md
- operator/internal/handlers/lokistack_create_or_update.go
- operator/internal/handlers/lokistack_create_or_update_test.go
- operator/internal/manifests/build_test.go
- operator/internal/manifests/config.go
- operator/internal/manifests/config_test.go
- operator/internal/manifests/gateway.go
- operator/internal/manifests/gateway_tenants.go
- operator/internal/manifests/gateway_tenants_test.go
- operator/internal/manifests/gateway_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
- operator/internal/manifests/openshift/build_test.go
- operator/internal/manifests/openshift/options.go
- operator/internal/manifests/openshift/route.go
- operator/internal/manifests/openshift/var.go
- operator/internal/manifests/options.go
- operator/internal/manifests/options_test.go
- operator/internal/manifests/service_test.go
- operator/internal/manifests/var.go
The present PR is a backport of managing server timeouts based on query timeout CR settings.
Ref: [LOG-4052](https://issues.redhat.com//browse/LOG-4052)
Depends on: 
- openshift/loki/pull/140
> [release-5.7] Backport PR grafana/loki#9405

- Dockerfile.ocp
- Dockerfile.promtail.ocp
Updates both loki and promtail Drockerfiles to RHEL 9 part of https://issues.redhat.com/browse/LOG-4054
**Checklist**
> build: update loki and promtail Dockerfile base image to RHEL 9

- Dockerfile.ocp
- Dockerfile.promtail.ocp
Updates both loki and promtail Drockerfiles to RHEL 9 part of [issues.redhat.com/browse/LOG-4054](https://issues.redhat.com/browse/LOG-4054)
The PR caused problems in our dev environments.**What this PR does / why we need it**:
**Checklist**
> backport: update loki and promtail Dockerfile base image to RHEL 9

- operator/CHANGELOG.md
- operator/controllers/loki/lokistack_controller.go
Description:
The present PR is a backport of the fix for the handling of conditions in the status.
Ref: [LOG-4156](https://issues.redhat.com//browse/LOG-4156)
> [release-5.7] Backport PR grafana/loki#9511

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
This PR is a backport for fixing runtime-config SHA1 compilation to release-5.7
Fixes [LOG-4161](https://issues.redhat.com/browse/LOG-4161) - Updating the RulerConfig CR can now trigger the restart of the ruler pod (and thus reflecting the changes to the user-workload AM)
**Checklist**
> [release-5.7] Include runtime-config in compiling the SHA1 checksum

- operator/CHANGELOG.md
- operator/internal/manifests/options.go
- operator/internal/manifests/options_test.go
Description:
The present PR is a backport for `release-5.7` of the fix for a nil-pointer dereference in the timeout config constructor
Ref: [LOG-4198](https://issues.redhat.com//browse/LOG-4198)
> [release-5.7] Backport PR grafana/loki#9623

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/apis/loki/v1beta1/lokistack_types_test.go
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
- operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/docs/lokistack/sop.md
- operator/docs/operator/api.md
- operator/internal/manifests/config_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/loki-runtime-config.yaml
- operator/internal/manifests/internal/sizes.go
Description:
The present PR is a backport for `release-5.7` of the per_stream limit ingestion settings.
> [release-5.7] Backport PR grafana/loki#9630

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
- operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
- operator/docs/lokistack/sop.md
- operator/docs/operator/api.md
- operator/internal/manifests/config_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/loki-runtime-config.yaml
- operator/internal/manifests/internal/sizes.go
Description:
The present PR is a backport for `release-5.6` of the per_stream limit ingestion settings.
> [release-5.6] Backport PR grafana/loki#9630

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
This PR backports the Loki operand bump from `2.8.0` to `2.8.3` for `release-5.6`
Ref: [LOG-4340](https://issues.redhat.com//browse/LOG-4340)
> [release-5.6] Backport PR grafana/loki#10019

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
This PR backports the Loki operand bump from `2.8.0` to `2.8.3` for `release-5.7`
Ref: [LOG-4340](https://issues.redhat.com//browse/LOG-4340)
> [release-5.7] Backport PR grafana/loki#10019

- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/openshift/manifests/loki-operator-manager-config_v1_configmap.yaml
- operator/bundle/openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operator/bundle/openshift/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- operator/bundle/openshift/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
- operator/bundle/openshift/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
- operator/bundle/openshift/manifests/loki-operator-webhook-service_v1_service.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_alertingrules.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_recordingrules.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_rulerconfigs.yaml
- operator/config/overlays/openshift/kustomization.yaml
Fix for downstream bundle builds to properly replace the labels in bundle manifests:
https://pkgs.devel.redhat.com/git/containers/loki-operator-bundle/tree/manifests/loki.grafana.com_alertingrules.yaml?h=openshift-logging-5.7-rhel-8#n7
as it used to be in 5.6 and previous builds:
https://pkgs.devel.redhat.com/git/containers/loki-operator-bundle/tree/manifests/loki.grafana.com_alertingrules.yaml?h=openshift-logging-5.6-rhel-8#n7
This issue arised from merging this upstream PR:
- grafana/loki/pull/7308
> [release-5.7] Fix openshift bundle manifest labels

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
This PR backports the Loki operand bump from `2.8.3` to `2.9.0` for release-5.7
Ref: [LOG-4492](https://issues.redhat.com//browse/LOG-4492)
> [release-5.7] Backport PR grafana/loki#10539

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
This PR backports the Loki operand bump from `2.9.0` to `2.9.1` for `release-5.7`
Ref: [LOG-4519](https://issues.redhat.com//browse/LOG-4519)
> [release-5.7] Backport PR grafana/loki#10600

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
This PR backports the Loki operand bump from `2.8.3` to `2.9.1` for `release-5.6`
Ref: [LOG-4519](https://issues.redhat.com//browse/LOG-4519)
> [release-5.6] Backport PR grafana/loki#10600

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/apis/loki/v1/lokistack_webhook.go
- operator/apis/loki/v1/lokistack_webhook_test.go
- operator/apis/loki/v1/v1.go
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
- operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
- operator/docs/operator/api.md
- operator/internal/manifests/config.go
- operator/internal/manifests/config_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
- operator/internal/manifests/memberlist.go
- operator/internal/manifests/var.go
Bakports the memberlist IPv6 support to `release-5.6`
Ref: [LOG-4570](https://issues.redhat.com//browse/LOG-4570) 
> [release-5.6] Backport PR grafana/loki#10562

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/apis/loki/v1/v1.go
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
- operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
- operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/docs/operator/api.md
- operator/internal/manifests/config.go
- operator/internal/manifests/config_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
- operator/internal/manifests/memberlist.go
- operator/internal/manifests/var.go
- operator/internal/validation/lokistack.go
- operator/internal/validation/lokistack_test.go
Bakports the memberlist IPv6 support to `release-5.7`
Ref: [LOG-4569](https://issues.redhat.com//browse/LOG-4569)
> [release-5.7] Backport PR grafana/loki#10562

- operator/CHANGELOG.md
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/jsonnet/config.libsonnet
Bakports the missing retention dashboard panels into `release-5.8`
Ref: [LOG-4610](https://issues.redhat.com//browse/LOG-4610)
Depends on:
- openshift/release/pull/44291
> [release-5.8] Backport PR grafana/loki#10854

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Backports the loki operand update from `v2.9.1` to `v2.9.2`
Refs: [LOG-4657](https://issues.redhat.com//browse/LOG-4657)
> [release-5.8] Backport PR grafana/loki#10924

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backports the loki operand update from `v2.9.1` to `v2.9.2`
Refs: [LOG-4657](https://issues.redhat.com//browse/LOG-4657)
> [release-5.7] Backport PR grafana/loki#10924

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backports the loki operand update from `v2.9.1` to `v2.9.2`
Refs: [LOG-4657](https://issues.redhat.com//browse/LOG-4657)
> [release-5.6] Backport PR grafana/loki#10924

- operator/CHANGELOG.md
- operator/internal/manifests/ruler.go
Backport ruler CA fixes for `release-5.8`
Refs: [LOG-4836](https://issues.redhat.com//browse/LOG-4836)
> [release-5.8] Backport PR grafana/loki#11288

- operator/CHANGELOG.md
- operator/internal/manifests/ruler.go
Backport ruler CA fixes for `release-5.6`
Refs: [LOG-4838](https://issues.redhat.com//browse/LOG-4838)
> [release-5.6] Backport PR grafana/loki#11288

- operator/CHANGELOG.md
- operator/internal/manifests/ruler.go
Backport ruler CA fixes for `release-5.7`
Refs: [LOG-4837](https://issues.redhat.com//browse/LOG-4837)
> [release-5.7] Backport PR grafana/loki#11288

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Backport Loki upgrade from `v2.9.2` to `v2.9.3` into `release-5.8`
Refs:
- [LOG-4872](https://issues.redhat.com//browse/LOG-4872)
> [release-5.8] Backport PR grafana/loki#11448

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki upgrade from `v2.9.2` to `v2.9.3` into `release-5.7`
Refs:
- [LOG-4872](https://issues.redhat.com//browse/LOG-4872)
> [release-5.7] Backport PR grafana/loki#11448

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki upgrade from `v2.9.2` to `v2.9.3` into `release-5.6`
Refs:
- [LOG-4872](https://issues.redhat.com//browse/LOG-4872)
> [release-5.6] Backport PR grafana/loki#11448

- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/rbac/role.yaml
- operator/controllers/loki/lokistack_controller.go
- operator/internal/manifests/openshift/rbac.go
Updated RBAC now match the new updated requirements by UWM Alertmanager introduced on: https://github.com/openshift/cluster-monitoring-operator/pull/2099
> [release-5.8] Backport PR grafana/loki#11620

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport operand upgrade Loki from `2.9.3` to `2.9.4` to `release-5.8`
Refs: [LOG-5011](https://issues.redhat.com//browse/LOG-5011)
> [release-5.8] Backport PR grafana/loki#11778

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport operand upgrade Loki from `2.9.3` to `2.9.4` to `release-5.7`
Refs: [LOG-5011](https://issues.redhat.com//browse/LOG-5011)
> [release-5.7] Backport PR grafana/loki#11778

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport operand upgrade Loki from `2.9.3` to `2.9.4` to `release-5.6`
Refs: [LOG-5011](https://issues.redhat.com//browse/LOG-5011)
> [release-5.6] Backport PR grafana/loki#11778

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/handlers/internal/storage/storage_test.go
This is a backport of grafana/loki#11824 to 5.6. Implements [LOG-5060](https://issues.redhat.com//browse/LOG-5060).
> LOG-5060: Improve messages for errors in storage secret

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/handlers/internal/storage/storage_test.go
This is a backport of grafana/loki#11824 to 5.8. Implements [LOG-5058](https://issues.redhat.com//browse/LOG-5058).
> LOG-5058: Improve messages for errors in storage secret

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/handlers/internal/storage/storage_test.go
This is a backport of grafana/loki#11824 to 5.7. Implements [LOG-5059](https://issues.redhat.com//browse/LOG-5059).
> LOG-5059: Improve messages for errors in storage secret

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/apis/loki/v1beta1/lokistack_types.go
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/docs/operator/api.md
- operator/internal/status/components.go
- operator/internal/status/components_test.go
- operator/internal/status/lokistack.go
- operator/internal/status/lokistack_test.go
- operator/internal/status/status_test.go
This is a backport of grafana/loki#11968 to 5.8. Implements [LOG-5171](https://issues.redhat.com//browse/LOG-5171).
> LOG-5171: Extend status to show difference between running and ready

- operator/CHANGELOG.md
- operator/apis/loki/v1/lokistack_types.go
- operator/apis/loki/v1beta1/lokistack_types.go
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/docs/operator/api.md
- operator/internal/status/components.go
- operator/internal/status/components_test.go
- operator/internal/status/lokistack.go
- operator/internal/status/lokistack_test.go
- operator/internal/status/status_test.go
This is a backport of grafana/loki#11968 to 5.7. Implements [LOG-5172](https://issues.redhat.com//browse/LOG-5172).
> LOG-5172: Extend status to show difference between running and ready

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operator/bundle/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manager/manager.yaml
- operator/config/overlays/openshift/kustomization.yaml
- operator/config/overlays/openshift/manager_metrics_secret_token.yaml
- operator/config/overlays/openshift/prometheus_service_monitor_patch.yaml
- operator/config/overlays/production/prometheus_service_monitor_patch.yaml
- operator/config/prometheus/monitor.yaml
- operator/config/rbac/auth_proxy_client_clusterrolebinding.yaml
- operator/config/rbac/auth_proxy_client_serviceaccount.yaml
- operator/config/rbac/auth_proxy_role_binding.yaml
- operator/config/rbac/auth_proxy_service.yaml
- operator/config/rbac/kustomization.yaml
- operator/config/rbac/role_binding.yaml
- operator/config/rbac/serviceaccount.yaml
Backporting PRs for operator metrics support in UWM environments in `release-5.6`
Refs: [LOG-5242](https://issues.redhat.com//browse/LOG-5242), [LOG-5252](https://issues.redhat.com//browse/LOG-5252)
> [release-5.6] Backport PR grafana/loki#12164 and grafana/loki#12216

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/community-openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/community/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/community/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manager/manager.yaml
- operator/config/overlays/community-openshift/prometheus_service_monitor_patch.yaml
- operator/config/overlays/openshift/kustomization.yaml
- operator/config/overlays/openshift/manager_metrics_secret_token.yaml
- operator/config/overlays/openshift/prometheus_service_monitor_patch.yaml
- operator/config/prometheus/monitor.yaml
- operator/config/rbac/auth_proxy_client_clusterrolebinding.yaml
- operator/config/rbac/auth_proxy_client_serviceaccount.yaml
- operator/config/rbac/auth_proxy_role_binding.yaml
- operator/config/rbac/auth_proxy_service.yaml
- operator/config/rbac/kustomization.yaml
- operator/config/rbac/role_binding.yaml
- operator/config/rbac/serviceaccount.yaml
Backporting PRs for operator metrics support in UWM environments in `release-5.8`
Refs: [LOG-5240](https://issues.redhat.com//browse/LOG-5240), [LOG-5250](https://issues.redhat.com//browse/LOG-5250)
> [release-5.8] Backport PR grafana/loki#12164 and grafana/loki#12216

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operator/bundle/community-openshift/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/community-openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/community/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/community/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-reader_v1_serviceaccount.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-token_v1_secret.yaml
- operator/bundle/openshift/manifests/loki-operator-controller-manager-read-metrics_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- operator/bundle/openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manager/manager.yaml
- operator/config/overlays/community-openshift/prometheus_service_monitor_patch.yaml
- operator/config/overlays/openshift/kustomization.yaml
- operator/config/overlays/openshift/manager_metrics_secret_token.yaml
- operator/config/overlays/openshift/prometheus_service_monitor_patch.yaml
- operator/config/prometheus/monitor.yaml
- operator/config/rbac/auth_proxy_client_clusterrolebinding.yaml
- operator/config/rbac/auth_proxy_client_serviceaccount.yaml
- operator/config/rbac/auth_proxy_role_binding.yaml
- operator/config/rbac/auth_proxy_service.yaml
- operator/config/rbac/kustomization.yaml
- operator/config/rbac/role_binding.yaml
- operator/config/rbac/serviceaccount.yaml
Backporting PRs for operator metrics support in UWM environments in `release-5.7`
Refs: [LOG-5241](https://issues.redhat.com//browse/LOG-5241), [LOG-5251](https://issues.redhat.com//browse/LOG-5251)
> [release-5.7] Backport PR grafana/loki#12164 and grafana/loki#12216

- operator/bundle/openshift/metadata/properties.yaml
Bump Max OpenShift Version to `4.16` to keep existing installations from raising `IncompatibleOperatorsInstalled` alerts.
> LOG-5272: Bump max OpenShift version to 4.16

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport operand upgrade Loki from `2.9.4` to `2.9.6` to `release-5.8`
Refs: [LOG-5278](https://issues.redhat.com//browse/LOG-5278)
> [release-5.8] Backport PR grafana/loki#12370

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport operand upgrade Loki from `2.9.4` to `2.9.6` to `release-5.7`
Refs: [LOG-5278](https://issues.redhat.com//browse/LOG-5278)
> [release-5.7] Backport PR grafana/loki#12370

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport operand upgrade Loki from `2.9.4` to `2.9.6` to `release-5.6`
Refs: [LOG-5278](https://issues.redhat.com//browse/LOG-5278)
> [release-5.6] Backport PR grafana/loki#12370

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/handlers/internal/storage/storage_test.go
- operator/internal/handlers/lokistack_create_or_update_test.go
This PR adds a validation step to verify that the endpoint URL is of the pattern https://s3.REGION.amazonaws.com when Amazon AWS S3 is used.
Fixes [LOG-5392](https://issues.redhat.com/browse/LOG-5392)
**Checklist**
> [release-5.8] Improve validation of provided S3 storage configuration

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/handlers/internal/storage/storage_test.go
- operator/internal/handlers/lokistack_create_or_update_test.go
This PR adds a validation step to verify that the endpoint URL is of the pattern `https://s3.REGION.amazonaws.com` when Amazon AWS S3 is used.
Fixes [LOG-5395](https://issues.redhat.com/browse/LOG-5395)
**Checklist**
> [release-5.9] Improve validation of provided S3 storage configuration

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/storage/options.go
Change Loki's configuration to use [virtual-host-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access) instead of path-style URLs when the object storage endpoint is AWS S3.
Fixes [LOG-5403](https://issues.redhat.com/browse/LOG-5403)
**Checklist**
> [release-5.7] Configure Loki to use virtual-host-style URLs for S3 AWS endpoints

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/storage/options.go
Change Loki's configuration to use [virtual-host-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access) instead of path-style URLs when the object storage endpoint is AWS S3.
Fixes [LOG-5402](https://issues.redhat.com/browse/LOG-5402)
**Checklist**
> [release-5.8] Configure Loki to use virtual-host-style URLs for S3 AWS endpoints

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/storage/options.go
Change Loki's configuration to use [virtual-host-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access) instead of path-style URLs when the object storage endpoint is AWS S3.
Fixes [LOG-5401](https://issues.redhat.com/browse/LOG-5401)
**Checklist**
> [release-5.9] Configure Loki to use virtual-host-style URLs for S3 AWS endpoints

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki operand bump to `v2.9.8` to `release-5.9`.
Refs: [LOG-5504](https://issues.redhat.com//browse/LOG-5504)
> [release-5.9] Backport PR grafana/loki#12874

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki operand bump to `v2.9.8` to `release-5.8`.
Refs: [LOG-5504](https://issues.redhat.com//browse/LOG-5504)
> [release-5.8] Backport PR grafana/loki#12874

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki operand bump to `v2.9.8` to `release-5.7`.
Refs: [LOG-5504](https://issues.redhat.com//browse/LOG-5504)
> [release-5.7] Backport PR grafana/loki#12874

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki operand bump to `v2.9.8` to `release-5.6`.
Refs: [LOG-5504](https://issues.redhat.com//browse/LOG-5504)
> [release-5.6] Backport PR grafana/loki#12874

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/options.go
This is a backport of grafana/loki#13066 to `release-5.9`.
Fixes [LOG-5614](https://issues.redhat.com//browse/LOG-5614)
> LOG-5614: Use a minimum value for replay memory ceiling

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/options.go
This is a backport of grafana/loki#13066 to `release-5.8`.
Fixes [LOG-5615](https://issues.redhat.com//browse/LOG-5615)
> LOG-5415: Use a minimum value for replay memory ceiling

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/options.go
This is a backport of grafana/loki#13066 to `release-5.7`.
Fixes [LOG-5616](https://issues.redhat.com//browse/LOG-5616)
> LOG-5616: Use a minimum value for replay memory ceiling

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/options.go
This is a backport of grafana/loki#13066 to `release-5.6`.
Fixes [LOG-5617](https://issues.redhat.com//browse/LOG-5617)
> LOG-5617: Use a minimum value for replay memory ceiling

- operator/CHANGELOG.md
- operator/controllers/loki/lokistack_controller.go
- operator/controllers/loki/lokistack_controller_test.go
Backport fix to enable `release-5.9` installations on CRC.
Refs: [LOG-5701](https://issues.redhat.com//browse/LOG-5701)
> [release-5.9] Backport PR grafana/loki#13299

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/var.go
Backport Loki operand update to `v3.1.0` into `release-5.9`
> [release-5.9] Backport PR grafana/loki#13422

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/var.go
Backport Loki operand update to `v3.1.0` into `release-5.6`
> [release-5.6] Backport PR grafana/loki#13422

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/var.go
Backport Loki operand update to `v3.1.0` into `release-5.8`
> [release-5.8] Backport PR grafana/loki#13422

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Follow-up fix to set `allow_stuctured_metadata: false` for `release-5.8` missing support for object storage schema version `v13`. The wrong default `allow_structured_metadata: true` was introduced accidentaly with the last Loki update from `v2.9.8` to `v3.1.0` by:
- openshift/loki/pull/317
Ref: LOG-5761, [LOG-5778](https://issues.redhat.com//browse/LOG-5778)
> [release-5.6] fix(operator): Disable structured metadata

- operator/CHANGELOG.md
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
- operator/jsonnet/config.libsonnet
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Backport support v3.1.0 in OpenShift dashboards into `release-5.9`
> [release-5.9] Backport PR grafana/loki#13430

- operator/CHANGELOG.md
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
- operator/jsonnet/config.libsonnet
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Backport support v3.1.0 in OpenShift dashboards into `release-5.8`
> [release-5.8] Backport PR grafana/loki#13430

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Backport missing PR that removes the deprecated field `querier.engine.timeout` in favor of the `limits_config.query_timeout` into `release-5.6`.
Refs: LOG-5761, [LOG-5778](https://issues.redhat.com//browse/LOG-5778)
> [release-5.6] Backport PR grafana/loki#8579

- operator/CHANGELOG.md
- operator/internal/manifests/mutate.go
Backport skipping serviceaccount annotations update patch into `release-5.9`
> [release-5.9] Backport PR grafana/loki#13450

- operator/CHANGELOG.md
- operator/internal/manifests/mutate.go
Backport skipping serviceaccount annotations update patch into `release-5.8`
> [release-5.8] Backport PR grafana/loki#13450

- operator/CHANGELOG.md
- operator/internal/handlers/internal/storage/storage.go
- operator/internal/handlers/internal/storage/storage_test.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/storage/options.go
Backport setting `allow_structured_metadata: true` only when a schema version `v13` or newer is provided and becomes active into `release-5.9`
Refs: 
- [LOG-5761](https://issues.redhat.com//browse/LOG-5761)
- [LOG-5778](https://issues.redhat.com//browse/LOG-5778)
> [release-5.9] Backport PR grafana/loki#13463

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Backport setting object storage for delete requests when using retention into `release-5.6`.
Ref: [LOG-5761](https://issues.redhat.com//browse/LOG-5761)
> [release-5.6] Backport PR for grafana/loki#13562

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Backport setting object storage for delete requests when using retention into `release-5.8`.
Ref: [LOG-5821](https://issues.redhat.com//browse/LOG-5821)
> [release-5.8] Backport PR for grafana/loki#13562

- operator/CHANGELOG.md
- operator/internal/status/conditions.go
- operator/internal/status/conditions_test.go
Backport of grafana/loki#13497 to `release-5.9`.
Fixes [LOG-5855](https://issues.redhat.com//browse/LOG-5855)
> [release-5.9] operator: Remove duplicate conditions from status

- operator/CHANGELOG.md
- operator/docs/lokistack/sop.md
- operator/internal/manifests/internal/alerts/prometheus-alerts.yaml
- operator/internal/manifests/internal/alerts/testdata/test.yaml
Backport of grafana/loki#13512 to `release-5.9`.
Fixes [LOG-5895](https://issues.redhat.com//browse/LOG-5895)
> [release-5.9] operator: Add alert for discarded samples

- operator/CHANGELOG.md
- operator/docs/lokistack/sop.md
- operator/internal/manifests/internal/alerts/prometheus-alerts.yaml
- operator/internal/manifests/internal/alerts/testdata/test.yaml
Backport of grafana/loki#13512 to `release-5.8`.
Fixes [LOG-5896](https://issues.redhat.com//browse/LOG-5896)
> [release-5.8] operator: Add alert for discarded samples

- operator/CHANGELOG.md
- operator/internal/manifests/mutate.go
Backport ingress annotation handling in `release-5.9`.
Refs: [LOG-5945](https://issues.redhat.com//browse/LOG-5945)
> [release-5.9] Backport PR grafana/loki#13708

- operator/CHANGELOG.md
- operator/internal/manifests/mutate.go
Backport ingress annotation handling in `release-5.8`.
Refs: [LOG-5946](https://issues.redhat.com//browse/LOG-5946)
> [release-5.8] Backport PR grafana/loki#13708

- operator/CHANGELOG.md
- operator/internal/manifests/mutate.go
Backport ingress annotation handling in `release-5.6`.
Refs: [LOG-5947](https://issues.redhat.com//browse/LOG-5947)
> [release-5.6] Backport PR grafana/loki#13708

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki bump to `v3.1.1` to `release-5.6`.
Refs: [LOG-5950](https://issues.redhat.com//browse/LOG-5950)
> [release-5.6] Backport PR grafana/loki#14042

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki bump to `v3.1.1` to `release-5.8`.
Refs: [LOG-5950](https://issues.redhat.com//browse/LOG-5950)
> [release-5.8] Backport PR grafana/loki#14042

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Backport Loki bump to `v3.1.1` to `release-5.9`.
Refs: [LOG-5950](https://issues.redhat.com//browse/LOG-5950)
> [release-5.9] Backport PR grafana/loki#14042

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
Backport CSV annotations to declare FIPS support into `release-6.0`
Ref: [LOG-5752](https://issues.redhat.com//browse/LOG-5752)
> [release-6.0] Backport PR grafana/loki#14308

- operator/CHANGELOG.md
- operator/internal/status/components.go
- operator/internal/status/components_test.go
Backport component view initialization in OCP console when no pods in to `release-6.0`.
Refs: [LOG-6129](https://issues.redhat.com//browse/LOG-6129)
> [release-6.0] Backport PR grafana/loki#14314

- operator/CHANGELOG.md
- operator/internal/status/components.go
- operator/internal/status/components_test.go
Backport component view initialization in OCP console when no pods in to `release-5.9`.
Refs: [LOG-6183](https://issues.redhat.com//browse/LOG-6183)
> [release-5.9] Backport PR grafana/loki#14314

- operator/CHANGELOG.md
- operator/internal/status/components.go
- operator/internal/status/components_test.go
Backport component view initialization in OCP console when no pods in to `release-5.8`.
Refs: [LOG-6184](https://issues.redhat.com//browse/LOG-6184)
> [release-5.8] Backport PR grafana/loki#14314

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Update loki operand from `v3.1.1` to `v3.2.0` in `release-5.6`
Refs: [LOG-6159](https://issues.redhat.com//browse/LOG-6159)
> [release-5.6] Backport PR grafana/loki#14331

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Backport Loki upgrade from `v3.2.0` to `v3.2.1` into `release-5.8`
Refs: [LOG-6268](https://issues.redhat.com//browse/LOG-6268)
> [release-5.8] Backport PR grafana/loki#14526

- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Backport of grafana/loki#14506 to `release-5.8`.
> LOG-6256: Disable automatic discovery of service name

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Backport Loki upgrade from `v3.2.0` to `v3.2.1` into `release-5.9`
Refs: [LOG-6268](https://issues.redhat.com//browse/LOG-6268)
> [release-5.9] Backport PR grafana/loki#14526

- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Backport of grafana/loki#14506 to `release-5.9`.
> LOG-6295: Disable automatic discovery of service name

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
Backport of grafana/loki#14613 to `release-6.0`
> LOG-6320: Disable log level discovery for OpenShift tenancy modes

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
Backport of grafana/loki#14613 to `release-5.9`
> LOG-6321: Disable log level discovery for OpenShift tenancy modes

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
Backport of grafana/loki#14613 to `release-5.8`
> LOG-6322: Disable log level discovery for OpenShift tenancy modes

- operator/bundle/openshift/metadata/properties.yaml
Updates the maximum OpenShift version to match the supported versions range.
[LOG-6347](https://issues.redhat.com//browse/LOG-6347)
> LOG-6347: Update maximum OpenShift version to match supported range

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/internal/config/managed_auth.go
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/manifests/openshift/credentialsrequest.go
- operator/internal/manifests/storage/configure.go
- operator/internal/manifests/storage/configure_test.go
- operator/internal/manifests/storage/var.go
Add support for managed GCP WorkloadIdentity to `release-6.0`.
Refs: [LOG-6158](https://issues.redhat.com//browse/LOG-6158)
> [release-6.0] Backport PR grafana/loki#14752

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
- operator/internal/config/managed_auth.go
- operator/internal/handlers/internal/storage/secrets.go
- operator/internal/handlers/internal/storage/secrets_test.go
- operator/internal/manifests/openshift/credentialsrequest.go
- operator/internal/manifests/storage/configure.go
- operator/internal/manifests/storage/configure_test.go
- operator/internal/manifests/storage/var.go
Add support for managed GCP WorkloadIdentity to `release-6.1`.
Refs: [LOG-6158](https://issues.redhat.com//browse/LOG-6158)
> [release-6.1] Backport PR grafana/loki#14752

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Updates the Loki version used to 3.3.2
[LOG-6633](https://issues.redhat.com//browse/LOG-6633)
PTAL @JoaoBraveCoding
> LOG-6633: Update Loki operand to v3.3.2

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Updates the Loki version used to 3.3.2 in `release-6.0`.
[LOG-6634](https://issues.redhat.com//browse/LOG-6634)
PTAL @JoaoBraveCoding
> LOG-6634: Update Loki operand to v3.3.2

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Updates the Loki version used to 3.3.2 in `release-5.9`.
[LOG-6635](https://issues.redhat.com//browse/LOG-6635)
> LOG-6635: Update Loki operand to v3.3.2

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
- operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Updates the Loki version used to 3.3.2 in `release-5.8`.
[LOG-6636](https://issues.redhat.com//browse/LOG-6636)
> LOG-6636: Update Loki operand to v3.3.2

- operator/internal/manifests/internal/sizes.go
Backport of grafana/loki#16035 to `release-6.1`.
> LOG-6693: Fix minimum available ingesters for 1x.pico size

- operator/bundle/openshift/metadata/properties.yaml
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to existing behavior.
> LOG-6534: Update maximum OpenShift version to match supported range

- operator/bundle/openshift/metadata/properties.yaml
This reverts the change introduced in #405 , because we pushed the change out to the next release.
Refs [LOG-6534](https://issues.redhat.com//browse/LOG-6534)
> LOG-6534: Revert change due to changed release plans

- operator/CHANGELOG.md
- operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
- operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/community-openshift/manager_related_image_patch.yaml
- operator/config/overlays/community/manager_related_image_patch.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
- operator/jsonnet/jsonnetfile.json
- operator/jsonnet/jsonnetfile.lock.json
Updates the Loki version used to 3.4.2 in `release-6.0`.
https://issues.redhat.com/browse/LOG-6837
cc @xperimental
> LOG-6837: Update Loki operand to v3.4.2

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
This PR changes the Operator code, so that the delete worker count can never be zero. This happened for the `1x.pico` size introduced in Loki Operator 6.1
Fixes [LOG-6797](https://issues.redhat.com//browse/LOG-6797)
/cc @JoaoBraveCoding 
/hold wait for next z-stream
> LOG-6797: Select non-zero delete worker count for all sizes

- operator/bundle/openshift/metadata/properties.yaml
This reapplies the change introduced in #405 which was reverted in #412.
Fixes [LOG-6534](https://issues.redhat.com//browse/LOG-6534)
> LOG-6534: Reapply change to maximum OpenShift version

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Enables time-based sharding of streams in Loki.
Fixes [LOG-6991](https://issues.redhat.com//browse/LOG-6991)
> LOG-6991: Enable time-based stream-sharding

- operator/CHANGELOG.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
Backport of grafana/loki#17026 to `release-6.2`.
Fixes [LOG-6992](https://issues.redhat.com//browse/LOG-6992)
**Notes**
- This PR also includes the change to the CHANGELOG for the 6.2.0 release because this is the first change since the release (it pulls in the items from community release 0.8.0).
> LOG-6992: Update memberlist when ingester becomes unhealthy

- go.mod
- vendor/modules.txt
Backport of grafana/loki#17745 to `release-6.2` to fix build.
/cc @JoaoBraveCoding 
/hold do we want this in before the z-stream release?
> chore(deps): Remove unused consul dependency
