Dockerfile.ocp

- Test if CI is working
- After merge this should trigger an image build
/cc @brancz

remove stale comment and test CI pipeline

---

OWNERS

Add logging team members to OWNERS

---

operator/CHANGELOG.md
operator/internal/manifests/internal/sizes.go

Description:
This PR backports the Loki ingestion rate change.
Ref: https://issues.redhat.com/browse/LOG-3283
/cc @xperimental 

[release-5.5] Backport PR grafana/loki#7617

---

operator/CHANGELOG.md
operator/apis/loki/v1/lokistack_types.go
operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
operator/config/crd/bases/loki.grafana.com_lokistacks.yaml

Description:
This PR backports the `replicationFactor` change.
Ref: https://issues.redhat.com/browse/LOG-3297
cc: @xperimental 
assign: @periklis

[release 5.5] Backport PR grafana/7711

---

operator/CHANGELOG.md

Removes some entries that were added by mistake in #79.

[release-5.5] Fix changelog entries

---

operator/CHANGELOG.md
operator/internal/manifests/gateway.go
operator/internal/manifests/gateway_test.go

The present PR is a backport of lokistack-gateway replica fix.
Ref: [LOG-3478](https://issues.redhat.com//browse/LOG-3478)

[release-5.5] Backport PR grafana/loki#8068

---

operator/CHANGELOG.md
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go

Ref: [LOG-3660](https://issues.redhat.com//browse/LOG-3660)

Update from upstream repository

---

operator/CHANGELOG.md
operator/controllers/loki/lokistack_controller.go

Description:
The present PR is a backport of the fix for the handling of conditions in the status.
Ref: [LOG-4158](https://issues.redhat.com//browse/LOG-4158)

[release-5.6] Backport PR grafana/loki#9511

---

operator/CHANGELOG.md
operator/controllers/loki/lokistack_controller.go
operator/internal/handlers/internal/openshift/alertmanager.go
operator/internal/manifests/config_test.go
operator/internal/manifests/gateway_tenants.go
operator/internal/manifests/openshift/configure.go
operator/internal/manifests/openshift/var.go

Refs [LOG-4361](https://issues.redhat.com//browse/LOG-4361)

[release-5.7] Backport PR grafana/loki#9963

---

OWNERS

release-5.5: Add myself to reviewers

---

OWNERS

release-5.6: Add myself to reviewers

---

OWNERS

release-5.7: Add myself to reviewers

---

operator/CHANGELOG.md
operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml

Backport infra annotations for `release-5.6`
Refs:
- [LOG-4859](https://issues.redhat.com//browse/LOG-4859)

[release-5.6] Backport PR grafana/loki#11393

---

operator/CHANGELOG.md
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml

Backport infra annotations for `release-5.7`
Refs:
- [LOG-4859](https://issues.redhat.com//browse/LOG-4859)

[release-5.7] Backport PR grafana/loki#11393

---

operator/CHANGELOG.md
operator/cmd/loki-broker/main.go
operator/docs/lokistack/object_storage.md
operator/internal/handlers/internal/storage/secrets.go
operator/internal/handlers/internal/storage/secrets_test.go
operator/internal/manifests/compactor.go
operator/internal/manifests/compactor_test.go
operator/internal/manifests/config.go
operator/internal/manifests/distributor.go
operator/internal/manifests/distributor_test.go
operator/internal/manifests/gateway.go
operator/internal/manifests/gateway_test.go
operator/internal/manifests/indexgateway.go
operator/internal/manifests/indexgateway_test.go
operator/internal/manifests/ingester.go
operator/internal/manifests/ingester_test.go
operator/internal/manifests/internal/config/build_test.go
operator/internal/manifests/internal/config/loki-config.yaml
operator/internal/manifests/querier.go
operator/internal/manifests/querier_test.go
operator/internal/manifests/query-frontend.go
operator/internal/manifests/query-frontend_test.go
operator/internal/manifests/ruler.go
operator/internal/manifests/ruler_test.go
operator/internal/manifests/storage/configure.go
operator/internal/manifests/storage/configure_test.go
operator/internal/manifests/storage/options.go
operator/internal/manifests/storage/schema_test.go
operator/internal/manifests/storage/var.go
operator/internal/manifests/var.go

Backport moving sensitive out of the Loki ConfigMap for `release-5.8`
Refs:
- [LOG-4869](https://issues.redhat.com//browse/LOG-4869)

[release-5.8] Backport PR grafana/loki#11357

---

operator/CHANGELOG.md
operator/cmd/loki-broker/main.go
operator/internal/handlers/internal/storage/secrets.go
operator/internal/handlers/internal/storage/secrets_test.go
operator/internal/manifests/compactor.go
operator/internal/manifests/compactor_test.go
operator/internal/manifests/config.go
operator/internal/manifests/distributor.go
operator/internal/manifests/distributor_test.go
operator/internal/manifests/gateway.go
operator/internal/manifests/gateway_test.go
operator/internal/manifests/indexgateway.go
operator/internal/manifests/indexgateway_test.go
operator/internal/manifests/ingester.go
operator/internal/manifests/ingester_test.go
operator/internal/manifests/internal/config/build_test.go
operator/internal/manifests/internal/config/loki-config.yaml
operator/internal/manifests/querier.go
operator/internal/manifests/querier_test.go
operator/internal/manifests/query-frontend.go
operator/internal/manifests/query-frontend_test.go
operator/internal/manifests/ruler.go
operator/internal/manifests/ruler_test.go
operator/internal/manifests/storage/configure.go
operator/internal/manifests/storage/configure_test.go
operator/internal/manifests/storage/options.go
operator/internal/manifests/storage/schema_test.go
operator/internal/manifests/storage/var.go
operator/internal/manifests/var.go

Backport moving sensitive out of the Loki ConfigMap for `release-5.7`
Refs:
- [LOG-4870](https://issues.redhat.com//browse/LOG-4870)

[release-5.7] Backport PR grafana/loki#11357

---

operator/CHANGELOG.md
operator/cmd/loki-broker/main.go
operator/internal/handlers/internal/storage/secrets.go
operator/internal/handlers/internal/storage/secrets_test.go
operator/internal/manifests/compactor.go
operator/internal/manifests/compactor_test.go
operator/internal/manifests/config.go
operator/internal/manifests/distributor.go
operator/internal/manifests/distributor_test.go
operator/internal/manifests/gateway.go
operator/internal/manifests/gateway_test.go
operator/internal/manifests/indexgateway.go
operator/internal/manifests/indexgateway_test.go
operator/internal/manifests/ingester.go
operator/internal/manifests/ingester_test.go
operator/internal/manifests/internal/config/build_test.go
operator/internal/manifests/internal/config/loki-config.yaml
operator/internal/manifests/querier.go
operator/internal/manifests/querier_test.go
operator/internal/manifests/query-frontend.go
operator/internal/manifests/query-frontend_test.go
operator/internal/manifests/ruler.go
operator/internal/manifests/ruler_test.go
operator/internal/manifests/storage/configure.go
operator/internal/manifests/storage/configure_test.go
operator/internal/manifests/storage/options.go
operator/internal/manifests/storage/schema_test.go
operator/internal/manifests/storage/var.go
operator/internal/manifests/var.go

Backport moving sensitive out of the Loki ConfigMap for `release-5.6`
Refs:
- [LOG-4871](https://issues.redhat.com//browse/LOG-4871)

[release-5.6] Backport PR grafana/loki#11357

---

operator/internal/manifests/storage/configure.go

Backport refactoring for `ensureObjectStorageCredentials` introduced in #223 to `release-5.8`
Refs: [LOG-4869](https://issues.redhat.com//browse/LOG-4869)

[release-5.8] Backport PR grafana/loki#11531

---

operator/internal/manifests/storage/configure.go

Backport refactoring for `ensureObjectStorageCredentials` introduced in #225 to `release-5.6`
Refs: [LOG-4871](https://issues.redhat.com//browse/LOG-4871)

[release-5.6] Backport PR grafana/loki#11531

---

operator/internal/manifests/storage/configure.go

Backport refactoring for `ensureObjectStorageCredentials` introduced in #224 to `release-5.7`.
Refs: [LOG-4870](https://issues.redhat.com//browse/LOG-4870)

[release-5.7] Backport PR grafana/loki#11531

---

OWNERS

[release-5.9] Update OWNERS

---

OWNERS

[release-6.0] Update OWNERS

---

OWNERS

[release-6.1] Update OWNERS

---

OWNERS

[release-5.8] Update OWNERS

---

operator/internal/manifests/internal/config/build_test.go
operator/internal/manifests/internal/config/loki-config.yaml

https://issues.redhat.com/browse/LOG-7322

[release-6.1] fix(operator): Update memberlist when ingester becomes unhealthy

---

operator/internal/validation/openshift/alertingrule_test.go
operator/internal/validation/openshift/common.go
operator/internal/validation/openshift/recordingrule_test.go

https://issues.redhat.com/browse/LOG-7319

[release-6.0] fix(operator): update webhook validator for alerts/rules

---

operator/internal/validation/openshift/alertingrule_test.go
operator/internal/validation/openshift/common.go
operator/internal/validation/openshift/recordingrule_test.go

https://issues.redhat.com/browse/LOG-7318

[release-6.1] fix(operator): update webhook validator for alerts/rules
